[package]
name = "asset-with-wasm-assets-and-custom-lib-path"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/entry.rs"

[dependencies]
wasm-bindgen = "0.2.63"
web-sys = { version = "0.3.40", features = [ "console" ] }
