language: node_js

cache:
  # cache yarn
  yarn: true
  directories:
    # cache npm
    - $HOME/.npm
    - node_modules
    - $TRAVIS_BUILD_DIR/node_modules

    # cache parcel
    - $TRAVIS_BUILD_DIR/.cache

env:
  global:
    - secure: UL0jM3lnDmqFbdFC7S8YC+yzN2VIEljYqtcebNWNR1HVSO0ssXdsfKfryuLV0bi3kkUDXXkqNu/pkWMUqfpj4luZWg5QtPmLy6FniI1vWUejukE1ms+LjoeunnV8N4oS+2vOJ0hLKdblENLO8HxPApScGLFGfSdpEKOsERQjfkPnkBPCR3qzxpQesLklJSGB+CFntD7dc/JWVUMNVamRK8JPcZF1IVXZtsNSWcih5svrfo/mtfGK6e28rFx15dUJJRFr0BUBGPL9sTs1kb14SMJG+FsaepIBLLsfbKn9/9oWGiP0QqGQ6zHOWHyu2G6ORl/pdDgAkHYNi4FfcIBOLEcwO6Lgl1MOpBFqX2riVJBfdfo/ivt/ghcfHsl6NcJ+yjjXRHyGWu9GkokcM/PAEGr2orVf9zUEBrFuHueoVxoipjWR/3yZNjkAwAwgosZSkVcZLoXvWFY+l/DDYI5C0gVsHNqBDsadIRI/18byO+tQPJfqB+0h+cNcoV5kuUe63i+cGGjlpDD+bMR2MR7a5DncW0OTj8UBlIE1saNw2AG9us53UyTsImdx4rg9NNvjf6mkl1fqCwUVxyWmE8B9oAX/CkcKVFiynQZz3yBTXO7UJdNRKsfNsNnZuTZDYP5hKvaMsTBNdtXKOhjxJA9qQAnFN7n1zAdEQ+0R5Q4P4u8=
    - secure: DEsFeS4yo+udokTmfux4X3E940DkRDP3B3Lo0zzM8m5L0hWZ0wANv0Qgk2gxtW10uO71rJ/KFmZeMYbQ63Yq2yVm/pZq4Cu2KIAOPNPdbkD3wF2HrXmDmXxFNYVh5fYhKSXeZwyfxY+MIn9XRwFEsTs8bs0FKX7nRTNlpZa1jtjzkzb5ig/UEgXQysjaCq6EHupaDbrY/rt2RmSETgm33mXx2cfhQ4W3qeAMIYP38x2ttZLCyQIC+peK5gHbmJSo/NTqwxTwn3bzH1hOx9F9oibHjFQrUSnWvOJy2MMpbFDzZ+Ih1HvyncM0DE/kKjZXJZW2xAabolfryhEVNIEUamjfAbCDKWWXuAwBiffSDdVfnYfH3w9jNr/9K9xw50p4CTB6IzGUCyloqD74gJJZH3P5z05ScpTFjwqmfq5/qXQTyEO/ROrgP/s2oiK315zSTH7ur9gz9W+OCEeqsEUzvKtHVHKCleElRG18YrHw+DUGunaReRj8tL20InyNvTGhY9zHP6wBIlNpgjYHvWC8jRw6KIIjucu54/zSiljVi14N1p7d9oghefYblmeyLYwMHrmAoRhbifqpwkJcG9wDeizFQ08r8Rw9bYAvN1AVett8b8aqpd8xAyEEM/v6JEHYuqYVT44yVb4i/EmYKmqhki42pb5vKgBJWvKtWXHGsU8=
    - secure: VTSpClpMy5NzPJDYl4DNxrhBES+R3R/Lnsy9pgVKtxJcR1Q+N1lg9LgB1nqpF2fhsy01TEMBt7WcYQUtf5FQJCasY2BzTH12/DXd7eLcyjsc5XIaA0HogXwygBoiPKvfJ8UmhlmtLBVLlXRJ90iFuB+2rnblEqoZ9KjypEN7qT15N4qFvQMxVS2Yksn0IsWv+47EhQqF7wuloUkhSJU7mEK9sFFM32v+5fqvMGKTBmmapPSzB9krzCooyN48k1WPgr+TKkTX8Lf2fj/s9pXzOWTDrpGl5wVvf3YWsRfl6+yNFAF9cf+0edmBvjHJD+hDgo6eIRjzwFRQsodyhHLDaBYXdsYm2yOKJ2u8IdIkH5misJtH02QK7m9T9IJctoGQD1A0B4QIeVUxoJLYLBSlqLaLzemsjl5oz6CDMa1SgtAC39yeUJ5uh1rr6N9fr25802u+IsXVz5jXx5XuDpUSZM5p71vUbGVf68rXLUOAjGnc0Iluuta0T4PeCgeIQGzRnDebKYGOavP/FtllpXcDnhydq6DG/hh4DItz9B90/vCEq+Uq9vX6S4w50fSWDKhZtSkJTM84WwTUENCXDxZsSSNgix4/beHH1WozLWlNI3eHAQ22t4Nqp6xqlZC0mCDhj3ZRVJvpR2J5yYpJoHWBQA/zebBViLImzgzyMPZocqo=
    - secure: Y/dvzfEx3vLWC4Zml60dx3lwoOU5yxSpriFkg8vojUO/OqIK3SSlA5LT4iaaNX22WKXa8/nOMtBlxKEabuyOsgUkrBi7ZO9XFd2xiFMkmf6F2w0m1u6+yiU2iaoFFQX+Rg44cmQgAKmljjuM/8MahaIvfLBaRvlZgYU3eJ0peXrSplHTV7KWwmRQt6OrBcBfWxdxuTVaiqhY4ApFxwqkgUuValCWQ/ubboi5OiqFOK0ZG0wBVT6Ew0fwzAU9zj64Re1evCab5D4/YwFcpb0iow6RagQKI0zdQnm9k0oKNBFeMoBZe2NdOeaENuatkN24QVeJ7TPVwTjbrBxvsyWd8vj4ks/str2tuegbS2aNKJ6BWgq/ZwMFALv3dHDbpvh/cjX703oAo+2pyIB+gMT/i7OQD/ptiaoRZF+1QcTxIF+Cbdzj8mGCL8gKP7JDHq+xZ7QddepNbBqRuPQFbIDffpF2HKF7U7j5OPyUzse1Zl0cVqmiVvBsgFuRyndVHL/N2TCp8ZXStrK2axSFGU5yzuF+rgKA438DrIvNXMY+FwN0b+FWAgIyOohjOeM5rQqlD0G4GEXGZURQDR4W3wDz/GbtckpbDXV+8WN53gOc48jtGkZ42z9wvv6497NvUgjbdP0PjpmZHFduyVMWhAFs/WVDEljXVm+dTbK3eto1K20=

before_install:
  # get the right npm version
  - NPM_VERSION=`node -pe "require('./package.engines.json').npm"`
  - if [ `npm --version` != "$NPM_VERSION" ]; then
    npm install --global npm@${NPM_VERSION};
    fi

  # get the right yarn version
  - YARN_VERSION=`node -pe "require('./package.engines.json').yarn"`
  - if [ `yarn --version` != "$YARN_VERSION" ]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION;
    export PATH=$HOME/.yarn/bin:$PATH;
    fi

before_script:
  # code climate's coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - './cc-test-reporter before-build'

script:
  - yarn lint
  - yarn test

after_success:
  - test $TRAVIS_PULL_REQUEST != "false" && npx semantic-release-github-pr

deploy:
  # deploy a git tag, release notes, bump package.json, update READMEs
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master

after_script:
  # report coverage
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
